# Generated by Django 4.1.4 on 2023-01-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
                ('slide', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
