# Generated by Django 4.1.4 on 2023-01-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBotApp', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
