# Generated by Django 4.1.4 on 2023-01-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBotApp', '0003_delete_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
