# Generated by Django 4.1.4 on 2023-01-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatBotApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
