# Generated by Django 4.1.4 on 2023-01-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatBotApp', '0006_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
    ]
